### PR TITLE
Updated samples to 1.9

### PR DESCRIPTION
**Pull request by devdeeprc**

### CODE REVIEW

**Comment by camnewnham** [comment]
The new AR marker sample here (or https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/pull/154) doesn't work out of the box for me - have I misconfigured something?

I have:
1. Pulled this repo
2. Built and run
3. Force-quit app on device
4. Enabled camera permissions via HoloLens settings
5. Restarted app 

But no detections and nothing in the in-app unity log readout.  Have also tested with printed QR codes for sanity.

image

**Comment by devdeeprc** [comment]
@camnewnham can you try with the newest runtime? 113.2309.7002

**Comment by camnewnham** [comment]
> @camnewnham can you try with the newest runtime? 113.2309.7002

I don't have any updates pending via the Microsoft Store on HoloLens (based on https://learn.microsoft.com/en-us/windows/mixed-reality/develop/native/openxr-getting-started#getting-started-with-openxr-for-hololens-2)

Is there another way to update or do I need to be on an insider track?

**Comment by camnewnham** [comment]
Ah - yes makes sense the latest runtime is required. I'll wait till it's generally available :)

**Comment by devdeeprc** [comment]
> Ah - yes makes sense the latest runtime is required. I'll wait till it's generally available :)

If you would like to try it now, you can use the preview runtime using the instructions here: https://learn.microsoft.com/en-us/windows/mixed-reality/develop/native/openxr-getting-started#using-preview-extensions

**Pull request closed without merging**
